# Generated by Django 3.2.4 on 2021-06-26 10:13

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='post_image', verbose_name='img')),
                ('data', models.DateTimeField(verbose_name='data')),
                ('date', models.DateField(default=datetime.date.today)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('full_text', models.TextField(verbose_name='full_text')),
            ],
        ),
    ]
