# Generated by Django 3.2.4 on 2021-07-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_post_datetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
