# Generated by Django 3.2.4 on 2021-07-10 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
