# Generated by Django 3.2.4 on 2021-07-08 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_curs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='curs',
        ),
    ]
