# Generated by Django 3.2.4 on 2021-07-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_delete_curs'),
    ]

    operations = [
        migrations.CreateModel(
            name='carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img')),
                ('p', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Corusel',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Social_Network',
        ),
    ]
