# Generated by Django 3.2.4 on 2021-07-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_man'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('instagram', models.CharField(blank=True, max_length=100, verbose_name='Instagram')),
                ('twitter', models.CharField(blank=True, max_length=100, verbose_name='Twitter')),
                ('facebook', models.CharField(blank=True, max_length=100, verbose_name='Facebook')),
                ('site', models.CharField(blank=True, max_length=100, verbose_name='Offial site')),
                ('telephone', models.CharField(max_length=20, verbose_name='Telephone')),
            ],
        ),
    ]
