# Generated by Django 3.2.4 on 2021-07-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_social_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img')),
                ('data', models.DateTimeField(verbose_name='vaqti')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=200)),
            ],
        ),
    ]
