# Generated by Django 3.2.4 on 2021-07-14 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20210712_1148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='carousel',
        ),
    ]
