# Generated by Django 3.2.4 on 2021-07-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_delete_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=100)),
                ('title2', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='img')),
                ('p', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=50)),
            ],
        ),
    ]
