# Generated by Django 3.2.4 on 2021-07-14 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_carousel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='posts',
        ),
    ]
