# Generated by Django 3.2.4 on 2021-07-14 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_delete_posts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
