# Generated by Django 3.2.4 on 2021-07-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(blank=True, upload_to='img')),
                ('text1', models.CharField(blank=True, max_length=500)),
                ('title', models.CharField(max_length=100)),
                ('img2', models.ImageField(blank=True, upload_to='img')),
                ('text2', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
