# Generated by Django 3.2.4 on 2021-06-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('p1', models.TextField(max_length=20, verbose_name='ДЛИТЕЛЬНОСТЬ')),
                ('p2', models.TextField(max_length=20, verbose_name='ПОСЕЩАЕМОСТЬ')),
                ('p3', models.TextField(max_length=100, verbose_name='ВИД ОБУЧЕНИЯ')),
                ('p4', models.CharField(max_length=20, verbose_name='СТОИМОСТЬ')),
            ],
        ),
    ]
