# Generated by Django 3.2.4 on 2021-06-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurs',
            name='p1',
            field=models.CharField(max_length=20, verbose_name='ДЛИТЕЛЬНОСТЬ'),
        ),
        migrations.AlterField(
            model_name='kurs',
            name='p2',
            field=models.CharField(max_length=20, verbose_name='ПОСЕЩАЕМОСТЬ'),
        ),
        migrations.AlterField(
            model_name='kurs',
            name='p3',
            field=models.CharField(max_length=100, verbose_name='ВИД ОБУЧЕНИЯ'),
        ),
    ]
