# Generated by Django 3.2.4 on 2021-07-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurs', '0002_auto_20210628_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurs',
            name='p3',
            field=models.CharField(max_length=20, verbose_name='ВИД ОБУЧЕНИЯ'),
        ),
    ]
