# Generated by Django 3.2.4 on 2021-07-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurs', '0003_alter_kurs_p3'),
    ]

    operations = [
        migrations.CreateModel(
            name='port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='post_image')),
                ('title', models.CharField(max_length=20, verbose_name='title')),
                ('any_t', models.TextField(verbose_name='text')),
            ],
        ),
        migrations.DeleteModel(
            name='kurs',
        ),
    ]
