# Generated by Django 3.2.4 on 2021-07-05 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurs', '0004_auto_20210705_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='post_image', verbose_name='img')),
                ('date', models.DateField(default=datetime.date.today)),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('full_text', models.TextField(verbose_name='full_text')),
            ],
        ),
        migrations.DeleteModel(
            name='port',
        ),
    ]
