# Generated by Django 3.2.4 on 2021-07-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurs', '0005_auto_20210705_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('h1', models.CharField(max_length=100)),
                ('h2', models.CharField(max_length=100)),
                ('h3', models.CharField(max_length=100)),
                ('h4', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
