# Generated by Django 3.2.4 on 2021-07-10 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurs', '0009_kurs_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kurs_index',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
