# Generated by Django 3.2.4 on 2021-07-10 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kurs', '0010_auto_20210710_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Yunalishi')),
                ('muddati', models.IntegerField(help_text='oy', verbose_name='Davomiyligi')),
                ('dars_soni', models.IntegerField(help_text='haftasiga', verbose_name='Darslar soni')),
                ('group', models.CharField(choices=[('групповой', 'групповой'), ('индивидуальный', 'индивидуальный'), ('мини группа', 'мини группа')], max_length=255, verbose_name='Guruh shakli')),
                ('price', models.IntegerField(verbose_name='Narxi(oy)')),
                ('img', models.ImageField(blank=True, upload_to='course')),
                ('description', models.TextField(verbose_name='Tavsifi')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone number')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurs.course', verbose_name='Course')),
            ],
        ),
    ]
