# Generated by Django 3.2.4 on 2021-07-15 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurs', '0011_course_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
