# Generated by Django 3.2.4 on 2021-07-16 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurs', '0013_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
