# Generated by Django 3.2.4 on 2021-07-16 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurs', '0014_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone number')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurs.course', verbose_name='Course')),
            ],
        ),
    ]
